site_name: CTF Writeups
repo_url: https://github.com/harshit-jain52/ctf
site_url: https://harshit-jain52.github.io/ctf/
theme:
  name: material
  features:
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true

plugins:
  - search
  - awesome-pages
